language: android
jdk: oraclejdk8
sudo: false

notifications:
  email: false

android:
  components:
    - tools
    - tools
    - platform-tools
    - extra-android-support
    - tools
    - build-tools-25.0.2
    - android-25
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'extra-android-support-.+'

before_script:
  - android update sdk --no-ui --filter extra-android-m2repository,extra-google-m2repository

script: ./gradlew test -i